
OUTFILE NULL

DEFLINE SWAP FIR(WW,XX,YY,ZZ) CREATE.USER fir.v DEFCMD(SWAP.USER ORDER WW) DEFCMD(SWAP.USER COEFF_BITS XX) DEFCMD(SWAP.USER DIN_BITS YY) DEFCMD(SWAP.USER MAC_NUM ZZ)


##FIR(ORDER, COEFF_BITS, DIN_BITS, MAC_NUM)
FIR(3, 12, 8, 4)   ##parallel
FIR(3, 16, 24, 2)  ##Nserial
FIR(7, 8, 32, 1)   ##Serial

